# Generated by Django 4.2.1 on 2023-05-12 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="books",
            new_name="book",
        ),
    ]
